packages:
  - packages/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@types/node@24.13.6'
  - '@turbo/darwin-64@2.11.4'
  - '@turbo/darwin-arm64@2.11.4'
  - '@turbo/linux-64@2.11.4'
  - '@turbo/linux-arm64@2.11.4'
  - '@turbo/windows-64@2.11.4'
  - '@turbo/windows-arm64@2.11.4'
  - turbo@2.11.4
