import { mkdirSync, writeFileSync } from 'node:fs';
import { ruleHelpEntries } from '../src/check/rule-help.ts';

const sections = Object.entries(ruleHelpEntries).map(
  ([rule, help]) =>
    `## ${rule.replaceAll('/', '-')}\n\n${help.summary}\n\n\`\`\`ts\n${help.example}\n\`\`\`\n`,
);
mkdirSync(new URL('../docs/', import.meta.url), { recursive: true });
writeFileSync(
  new URL('../docs/rules.md', import.meta.url),
  `<!-- Generated by scripts/docs.ts from src/check/rule-help.ts. -->\n\n# Rule guide\n\n${sections.join('\n')}`,
);
